##### HOOKS #####
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check + format
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]

      - id: ty
        name: ty type check
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false

      - id: tach
        name: tach architecture check
        entry: uv run tach check
        language: system
        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
